-- =============================================
-- VADEMÉCUM VENEZOLANO - FÁRMACOS COMUNES
-- Datos iniciales para el sistema
-- =============================================

INSERT INTO vademecum (commercial_name, active_ingredient, presentation, concentration, route, usual_dose, category, controlled) VALUES

-- ANALGÉSICOS Y ANTIPIRÉTICOS
('Acetaminofén Coinfar', 'Paracetamol', 'Tabletas', '500mg', 'Oral', '500-1000mg cada 6-8h', 'Analgésico/Antipirético', false),
('Paracetamol Leti', 'Paracetamol', 'Tabletas', '500mg', 'Oral', '500-1000mg cada 6-8h', 'Analgésico/Antipirético', false),
('Pediatamol', 'Paracetamol', 'Jarabe', '120mg/5ml', 'Oral', '10-15mg/kg cada 6-8h', 'Analgésico/Antipirético', false),
('Analgan', 'Metamizol sódico', 'Tabletas', '500mg', 'Oral', '500mg-1g cada 8h', 'Analgésico', false),
('Dipirona Leti', 'Metamizol sódico', 'Ampolla', '1g/2ml', 'IV/IM', '1-2g cada 8h', 'Analgésico', false),
('Profenid', 'Ketoprofeno', 'Ampolla', '100mg', 'IV/IM', '100mg cada 8-12h', 'AINE', false),
('Voltaren', 'Diclofenaco', 'Tabletas', '50mg', 'Oral', '50mg cada 8h', 'AINE', false),
('Cataflam', 'Diclofenaco potásico', 'Tabletas', '50mg', 'Oral', '50mg cada 8-12h', 'AINE', false),
('Ibuprofeno Leti', 'Ibuprofeno', 'Tabletas', '400mg', 'Oral', '400mg cada 6-8h', 'AINE', false),
('Advil', 'Ibuprofeno', 'Tabletas', '200mg', 'Oral', '400mg cada 6-8h', 'AINE', false),
('Piroxicam Leti', 'Piroxicam', 'Tabletas', '20mg', 'Oral', '20mg una vez al día', 'AINE', false),
('Feldene', 'Piroxicam', 'Cápsulas', '20mg', 'Oral', '20mg una vez al día', 'AINE', false),
('Meloxicam Leti', 'Meloxicam', 'Tabletas', '15mg', 'Oral', '7.5-15mg una vez al día', 'AINE', false),
('Toradol', 'Ketorolaco', 'Ampolla', '30mg/ml', 'IV/IM', '15-30mg cada 6h (máx 5 días)', 'AINE', false),
('Tramal', 'Tramadol', 'Cápsulas', '50mg', 'Oral', '50-100mg cada 6-8h', 'Analgésico opioide', true),
('Tramadol Leti', 'Tramadol', 'Ampolla', '100mg/2ml', 'IV/IM', '100mg cada 8-12h', 'Analgésico opioide', true),
('Nalbufina Leti', 'Nalbufina', 'Ampolla', '10mg/ml', 'IV/IM/SC', '10mg cada 3-6h', 'Analgésico opioide', true),
('Morfina Leti', 'Morfina', 'Ampolla', '10mg/ml', 'IV/SC', '2-5mg IV o 5-10mg SC', 'Opioide', true),

-- ANTIBIÓTICOS
('Amoxicilina Coinfar', 'Amoxicilina', 'Cápsulas', '500mg', 'Oral', '500mg cada 8h', 'Antibiótico betalactámico', false),
('Amoxidal', 'Amoxicilina', 'Cápsulas', '500mg', 'Oral', '500mg cada 8h', 'Antibiótico betalactámico', false),
('Augmentin', 'Amoxicilina/Ácido clavulánico', 'Tabletas', '875/125mg', 'Oral', '875mg cada 12h', 'Antibiótico betalactámico', false),
('Clavamox', 'Amoxicilina/Ácido clavulánico', 'Tabletas', '875/125mg', 'Oral', '875mg cada 12h', 'Antibiótico betalactámico', false),
('Ciprofloxacina Leti', 'Ciprofloxacina', 'Tabletas', '500mg', 'Oral', '500mg cada 12h', 'Fluoroquinolona', false),
('Ciprobay', 'Ciprofloxacina', 'Tabletas', '500mg', 'Oral', '500mg cada 12h', 'Fluoroquinolona', false),
('Cipro IV', 'Ciprofloxacina', 'Frasco ampolla', '200mg/100ml', 'IV', '400mg cada 12h (inf. 60min)', 'Fluoroquinolona', false),
('Metronidazol Leti', 'Metronidazol', 'Tabletas', '500mg', 'Oral', '500mg cada 8h', 'Nitroimidazol', false),
('Flagyl IV', 'Metronidazol', 'Frasco', '500mg/100ml', 'IV', '500mg cada 8h (inf. 30min)', 'Nitroimidazol', false),
('Clindamicina Leti', 'Clindamicina', 'Cápsulas', '300mg', 'Oral', '300-450mg cada 6h', 'Lincosamida', false),
('Dalacin C', 'Clindamicina', 'Ampolla', '600mg/4ml', 'IV/IM', '600-900mg cada 8h', 'Lincosamida', false),
('Ceftriaxona Leti', 'Ceftriaxona', 'Frasco ampolla', '1g', 'IV/IM', '1-2g cada 24h', 'Cefalosporina 3ª gen.', false),
('Rocefin', 'Ceftriaxona', 'Frasco ampolla', '1g', 'IV/IM', '1-2g cada 24h', 'Cefalosporina 3ª gen.', false),
('Cefazolina Leti', 'Cefazolina', 'Frasco ampolla', '1g', 'IV/IM', '1-2g cada 8h', 'Cefalosporina 1ª gen.', false),
('Ampicilina/Sulbactam Leti', 'Ampicilina/Sulbactam', 'Frasco ampolla', '1.5g', 'IV', '1.5-3g cada 6-8h', 'Betalactámico', false),
('Unasyn', 'Ampicilina/Sulbactam', 'Frasco ampolla', '3g', 'IV', '3g cada 6h', 'Betalactámico', false),
('Gentamicina Leti', 'Gentamicina', 'Ampolla', '80mg/2ml', 'IV/IM', '3-5mg/kg/día', 'Aminoglucósido', false),
('Amikacina Leti', 'Amikacina', 'Ampolla', '500mg/2ml', 'IV/IM', '15mg/kg/día', 'Aminoglucósido', false),
('Meropenem Leti', 'Meropenem', 'Frasco ampolla', '500mg', 'IV', '500mg-1g cada 8h', 'Carbapenémico', false),
('Meronem', 'Meropenem', 'Frasco ampolla', '1g', 'IV', '1-2g cada 8h', 'Carbapenémico', false),
('Vancomicina Leti', 'Vancomicina', 'Frasco ampolla', '500mg', 'IV', '15-20mg/kg cada 12h', 'Glucopéptido', false),
('Doxiciclina Leti', 'Doxiciclina', 'Cápsulas', '100mg', 'Oral', '100mg cada 12h', 'Tetraciclina', false),
('Azitromicina Leti', 'Azitromicina', 'Tabletas', '500mg', 'Oral', '500mg una vez al día x 3 días', 'Macrólido', false),
('Zitromax', 'Azitromicina', 'Tabletas', '500mg', 'Oral', '500mg una vez al día x 3 días', 'Macrólido', false),
('Claritromicina Leti', 'Claritromicina', 'Tabletas', '500mg', 'Oral', '500mg cada 12h', 'Macrólido', false),
('Biaxin', 'Claritromicina', 'Tabletas', '500mg', 'Oral', '500mg cada 12h', 'Macrólido', false),
('Trimetoprim/Sulfametoxazol Leti', 'TMP/SMX', 'Tabletas', '160/800mg', 'Oral', '1 tableta cada 12h', 'Sulfonamida', false),
('Bactrim Forte', 'Trimetoprim/Sulfametoxazol', 'Tabletas', '160/800mg', 'Oral', '1 tableta cada 12h', 'Sulfonamida', false),
('Fluconazol Leti', 'Fluconazol', 'Cápsulas', '150mg', 'Oral', '150-400mg según indicación', 'Antifúngico', false),
('Diflucan', 'Fluconazol', 'Cápsulas', '150mg', 'Oral', '150mg dosis única (vaginal) o 400mg/d (sistémico)', 'Antifúngico', false),

-- CARDIOVASCULARES
('Enalapril Leti', 'Enalapril', 'Tabletas', '10mg', 'Oral', '5-20mg cada 12-24h', 'IECA', false),
('Losartán Leti', 'Losartán', 'Tabletas', '50mg', 'Oral', '50-100mg una vez al día', 'ARA-II', false),
('Amlodipina Leti', 'Amlodipina', 'Tabletas', '5mg', 'Oral', '5-10mg una vez al día', 'Bloqueador Ca', false),
('Norvasc', 'Amlodipina', 'Tabletas', '5mg', 'Oral', '5-10mg una vez al día', 'Bloqueador Ca', false),
('Atenolol Leti', 'Atenolol', 'Tabletas', '50mg', 'Oral', '25-100mg una vez al día', 'Betabloqueador', false),
('Metoprolol Leti', 'Metoprolol', 'Tabletas', '50mg', 'Oral', '50-100mg cada 12h', 'Betabloqueador', false),
('Bisoprolol Leti', 'Bisoprolol', 'Tabletas', '5mg', 'Oral', '5-10mg una vez al día', 'Betabloqueador', false),
('Furosemida Leti', 'Furosemida', 'Tabletas', '40mg', 'Oral', '40-80mg una vez al día', 'Diurético de asa', false),
('Lasix', 'Furosemida', 'Ampolla', '20mg/2ml', 'IV/IM', '20-40mg IV lento', 'Diurético de asa', false),
('Espironolactona Leti', 'Espironolactona', 'Tabletas', '25mg', 'Oral', '25-100mg una vez al día', 'Diurético ahorrador K', false),
('Nitroglicerina Leti', 'Nitroglicerina', 'Ampolla', '5mg/ml', 'IV', '5-200 mcg/min en infusión', 'Nitrato', false),
('Digoxina Leti', 'Digoxina', 'Tabletas', '0.25mg', 'Oral', '0.125-0.25mg una vez al día', 'Glucósido cardíaco', false),
('Amiodarona Leti', 'Amiodarona', 'Tabletas', '200mg', 'Oral', '200mg/día (mantenimiento)', 'Antiarrítmico', false),
('Cordarone IV', 'Amiodarona', 'Ampolla', '150mg/3ml', 'IV', '150mg en 10 min (carga)', 'Antiarrítmico', false),
('Atorvastatina Leti', 'Atorvastatina', 'Tabletas', '20mg', 'Oral', '10-80mg una vez al día', 'Estatina', false),
('Lipitor', 'Atorvastatina', 'Tabletas', '10mg', 'Oral', '10-80mg una vez al día', 'Estatina', false),

-- GASTROINTESTINALES
('Omeprazol Leti', 'Omeprazol', 'Cápsulas', '20mg', 'Oral', '20-40mg una vez al día', 'IBP', false),
('Losec', 'Omeprazol', 'Cápsulas', '20mg', 'Oral', '20-40mg una vez al día', 'IBP', false),
('Pantoprazol Leti', 'Pantoprazol', 'Tabletas', '40mg', 'Oral', '40mg una vez al día', 'IBP', false),
('Pantoloc', 'Pantoprazol', 'Frasco ampolla', '40mg', 'IV', '40mg IV una vez al día', 'IBP', false),
('Ranitidina Leti', 'Ranitidina', 'Tabletas', '150mg', 'Oral', '150mg cada 12h o 300mg una vez al día', 'Anti-H2', false),
('Metoclopramida Leti', 'Metoclopramida', 'Ampolla', '10mg/2ml', 'IV/IM', '10mg cada 8h', 'Procinético/Antiemético', false),
('Ondansetron Leti', 'Ondansetrón', 'Ampolla', '4mg/2ml', 'IV', '4-8mg cada 8h', 'Antiemético', false),
('Zofran', 'Ondansetrón', 'Ampolla', '4mg/2ml', 'IV', '4-8mg cada 8h', 'Antiemético', false),
('Dimenhidrinato Leti', 'Dimenhidrinato', 'Tabletas', '50mg', 'Oral', '50mg cada 4-6h', 'Antiemético', false),
('Biodramina', 'Dimenhidrinato', 'Tabletas', '50mg', 'Oral', '50mg cada 4-6h', 'Antiemético', false),
('Bismutol', 'Subsalicilato de bismuto', 'Suspensión', '87.5mg/5ml', 'Oral', '30ml cada 30 min (4 dosis)', 'Gastroprotector', false),
('Sucralfato Leti', 'Sucralfato', 'Tabletas', '1g', 'Oral', '1g cuatro veces al día', 'Gastroprotector', false),

-- ENDOCRINOLOGÍA
('Insulina Regular Lilly', 'Insulina regular', 'Frasco 10ml', '100 UI/ml', 'SC/IV', 'Según glucemia y esquema', 'Insulina', false),
('Humulin R', 'Insulina regular', 'Frasco 10ml', '100 UI/ml', 'SC/IV', 'Según esquema', 'Insulina', false),
('Insulina NPH Lilly', 'Insulina NPH', 'Frasco 10ml', '100 UI/ml', 'SC', 'Según esquema', 'Insulina', false),
('Metformina Leti', 'Metformina', 'Tabletas', '850mg', 'Oral', '850mg cada 12h con comidas', 'Hipoglucemiante oral', false),
('Glucofage', 'Metformina', 'Tabletas', '850mg', 'Oral', '850mg cada 12h con comidas', 'Hipoglucemiante oral', false),
('Glibenclamida Leti', 'Glibenclamida', 'Tabletas', '5mg', 'Oral', '2.5-15mg con desayuno', 'Sulfonilurea', false),
('Levotiroxina Leti', 'Levotiroxina', 'Tabletas', '100 mcg', 'Oral', '50-200 mcg en ayunas', 'Hormona tiroidea', false),
('Eutirox', 'Levotiroxina', 'Tabletas', '50 mcg', 'Oral', '50-200 mcg en ayunas', 'Hormona tiroidea', false),
('Hidrocortisona Leti', 'Hidrocortisona', 'Ampolla', '100mg', 'IV', '50-100mg cada 6-8h', 'Corticoide', false),
('Dexametasona Leti', 'Dexametasona', 'Ampolla', '4mg/ml', 'IV/IM', '4-8mg cada 6-8h', 'Corticoide', false),
('Decadrón', 'Dexametasona', 'Ampolla', '8mg/2ml', 'IV', '4-24mg según indicación', 'Corticoide', false),
('Metilprednisolona Leti', 'Metilprednisolona', 'Frasco ampolla', '125mg', 'IV', '10-500mg según indicación', 'Corticoide', false),
('Solu-Medrol', 'Metilprednisolona', 'Frasco ampolla', '125mg', 'IV', '10-500mg', 'Corticoide', false),
('Prednisona Leti', 'Prednisona', 'Tabletas', '5mg', 'Oral', '5-60mg al día', 'Corticoide', false),

-- RESPIRATORIO
('Salbutamol Leti', 'Salbutamol', 'Inhalador', '100mcg/dosis', 'Inhalado', '1-2 puff cada 4-6h', 'Broncodilatador B2', false),
('Ventolin', 'Salbutamol', 'Inhalador', '100mcg/dosis', 'Inhalado', '2 puff cada 4-6h', 'Broncodilatador B2', false),
('Salbutamol NF IV', 'Salbutamol', 'Ampolla', '0.5mg/ml', 'IV', '0.5mg SC o infusión IV', 'Broncodilatador B2', false),
('Budesonida Leti', 'Budesonida', 'Inhalador', '200mcg/dosis', 'Inhalado', '400-800mcg al día', 'Corticoide inhalado', false),
('Bromuro de Ipratropio Leti', 'Bromuro de ipratropio', 'Nebulización', '0.25mg/ml', 'Inhalado', '250-500 mcg cada 6-8h', 'Anticolinérgico', false),
('Atrovent', 'Bromuro de ipratropio', 'Inhalador', '20mcg/dosis', 'Inhalado', '2-3 puff cada 6-8h', 'Anticolinérgico', false),
('N-Acetilcisteína Leti', 'N-Acetilcisteína', 'Sobres', '600mg', 'Oral', '600mg cada 8-12h', 'Mucolítico/Antioxidante', false),
('Fluimucil', 'N-Acetilcisteína', 'Ampolla', '300mg/3ml', 'IV', '150mg/kg en 15 min', 'Antídoto/Mucolítico', false),

-- ANTICOAGULANTES
('Heparina Sódica Leti', 'Heparina sódica', 'Ampolla', '5000 UI/ml', 'IV/SC', 'Según protocolo', 'Anticoagulante', false),
('Enoxaparina Coinfar', 'Enoxaparina', 'Jeringa precargada', '40mg/0.4ml', 'SC', '40mg SC cada 24h (profilaxis)', 'HBPM', false),
('Clexane', 'Enoxaparina', 'Jeringa precargada', '60mg/0.6ml', 'SC', '1mg/kg cada 12h (tratamiento)', 'HBPM', false),
('Warfarina Leti', 'Warfarina', 'Tabletas', '5mg', 'Oral', 'Según INR objetivo', 'Anticoagulante oral', false),
('Coumadin', 'Warfarina', 'Tabletas', '2.5mg', 'Oral', 'Según INR', 'Anticoagulante oral', false),
('Rivaroxabán Leti', 'Rivaroxabán', 'Tabletas', '20mg', 'Oral', '20mg al día con la cena', 'ACOD', false),
('Xarelto', 'Rivaroxabán', 'Tabletas', '20mg', 'Oral', '20mg al día', 'ACOD', false),

-- NEUROLÓGICOS Y PSIQUIÁTRICOS
('Diazepam Leti', 'Diazepam', 'Tabletas', '5mg', 'Oral', '2-10mg según indicación', 'Benzodiacepina', true),
('Valium', 'Diazepam', 'Ampolla', '10mg/2ml', 'IV/IM', '5-10mg IV lento', 'Benzodiacepina', true),
('Midazolam Leti', 'Midazolam', 'Ampolla', '5mg/5ml', 'IV', 'Según protocolo de sedación', 'Benzodiacepina', true),
('Alprazolam Leti', 'Alprazolam', 'Tabletas', '0.5mg', 'Oral', '0.25-0.5mg cada 8h', 'Benzodiacepina', true),
('Clonazepam Leti', 'Clonazepam', 'Tabletas', '0.5mg', 'Oral', '0.5-2mg cada 8-12h', 'Benzodiacepina', true),
('Fenitoína Leti', 'Fenitoína', 'Ampolla', '250mg/5ml', 'IV', 'Según protocolo antiepiléptico', 'Antiepiléptico', false),
('Carbamazepina Leti', 'Carbamazepina', 'Tabletas', '200mg', 'Oral', '200mg cada 12h (inicio)', 'Antiepiléptico', false),
('Valproato Leti', 'Ácido valproico', 'Tabletas', '500mg', 'Oral', '250-500mg cada 8-12h', 'Antiepiléptico', false),
('Haloperidol Leti', 'Haloperidol', 'Ampolla', '5mg/ml', 'IV/IM', '2-5mg según indicación', 'Antipsicótico', false),
('Sertralina Leti', 'Sertralina', 'Tabletas', '50mg', 'Oral', '50-200mg una vez al día', 'ISRS', false),
('Fluoxetina Leti', 'Fluoxetina', 'Cápsulas', '20mg', 'Oral', '20mg una vez al día', 'ISRS', false),

-- SOLUCIONES PARENTERALES
('Cloruro de Sodio 0.9%', 'Cloruro de sodio', 'Frasco 1000ml', '0.9%', 'IV', '500-1000ml según estado hídrico', 'Solución isotónica', false),
('Dextrosa 5%', 'Glucosa', 'Frasco 500ml', '5%', 'IV', '500-1000ml según estado hídrico', 'Solución glucosada', false),
('Lactato de Ringer', 'Solución de Ringer', 'Frasco 1000ml', 'Isotónica', 'IV', '500-1000ml según estado hídrico', 'Solución cristaloide', false),
('Cloruro de Potasio', 'Cloruro de potasio', 'Ampolla', '2mEq/ml 10ml', 'IV', 'Diluir: 10-20 mEq/hora en infusión', 'Electrolito', false),
('Gluconato de Calcio', 'Gluconato de calcio', 'Ampolla', '10% 10ml', 'IV', '1g (10ml) IV lento en 10 min', 'Electrolito', false),
('Sulfato de Magnesio Leti', 'Sulfato de magnesio', 'Ampolla', '1g/2ml', 'IV', '1-2g IV en 5-10 min', 'Electrolito', false),
('Bicarbonato de Sodio Leti', 'Bicarbonato de sodio', 'Ampolla', '1mEq/ml 20ml', 'IV', 'Según déficit de bases', 'Alcalinizante', false),
('Albumina Humana 20%', 'Albúmina humana', 'Frasco 50ml', '20%', 'IV', '25-50g según indicación', 'Expansor oncótico', false),

-- ANTIHISTAMÍNICOS
('Loratadina Leti', 'Loratadina', 'Tabletas', '10mg', 'Oral', '10mg una vez al día', 'Antihistamínico', false),
('Claritin', 'Loratadina', 'Tabletas', '10mg', 'Oral', '10mg una vez al día', 'Antihistamínico', false),
('Cetirizina Leti', 'Cetirizina', 'Tabletas', '10mg', 'Oral', '10mg una vez al día', 'Antihistamínico', false),
('Difenhidramina Leti', 'Difenhidramina', 'Ampolla', '50mg/ml', 'IV/IM', '10-50mg cada 4-6h', 'Antihistamínico', false),
('Benadryl', 'Difenhidramina', 'Cápsulas', '25mg', 'Oral', '25-50mg cada 6-8h', 'Antihistamínico', false),
('Hidrocortisona+Difenhidramina', 'Dexametasona/Difenhidramina', 'Ampolla', '8mg+50mg', 'IV', '1 ampolla IV para reacciones alérgicas', 'Antialérgico', false),

-- OTROS FRECUENTES EN CIRUGÍA
('Esomeprazol Leti', 'Esomeprazol', 'Frasco ampolla', '40mg', 'IV', '40mg IV una vez al día', 'IBP', false),
('Vitamina K Leti', 'Fitomenadiona', 'Ampolla', '10mg/ml', 'IV/IM/SC', '2.5-10mg según indicación', 'Vitamina K', false),
('Ácido Tranexámico Leti', 'Ácido tranexámico', 'Ampolla', '500mg/5ml', 'IV', '1g en 10 min, luego 1g en 8h', 'Antifibrinolítico', false),
('Neostigmina Leti', 'Neostigmina', 'Ampolla', '0.5mg/ml', 'IV', '0.5-2.5mg IV con atropina', 'Inhibidor AChE', false),
('Atropina Leti', 'Atropina', 'Ampolla', '1mg/ml', 'IV', '0.5-1mg IV (repetir prn)', 'Anticolinérgico', false),
('Adrenalina Leti', 'Epinefrina', 'Ampolla', '1mg/ml', 'IV/IM', '0.5-1mg IM (anafilaxia) o 1mg IV (PCR)', 'Simpaticomimético', false),
('Naloxona Leti', 'Naloxona', 'Ampolla', '0.4mg/ml', 'IV/IM/SC', '0.4-2mg cada 2-3 min', 'Antagonista opioide', false),
('Flumazenil Leti', 'Flumazenil', 'Ampolla', '0.1mg/ml 10ml', 'IV', '0.2mg IV en 15 seg (repetir cada min)', 'Antagonista benzodiacepinas', false),
('Propofol Leti', 'Propofol', 'Frasco 20ml', '10mg/ml', 'IV', 'Según protocolo anestésico', 'Anestésico IV', false),
('Ketamina Leti', 'Ketamina', 'Ampolla', '500mg/10ml', 'IV/IM', '1-2mg/kg IV o 4-6mg/kg IM', 'Anestésico', true),
('Lidocaína Leti', 'Lidocaína', 'Ampolla', '2% 20ml', 'Local/IV', '3-4mg/kg (local) o 1mg/kg IV (arritmias)', 'Anestésico local/Antiarrítmico', false),
('Bupivacaína Leti', 'Bupivacaína', 'Ampolla', '0.5% 20ml', 'Local', 'Según protocolo anestésico', 'Anestésico local', false),

-- SUPLEMENTOS Y VITAMINAS
('Vitamina C Leti', 'Ácido ascórbico', 'Tabletas', '500mg', 'Oral', '500-1000mg una vez al día', 'Vitamina', false),
('Sulfato Ferroso Leti', 'Sulfato ferroso', 'Tabletas', '325mg', 'Oral', '325mg cada 8-12h en ayunas', 'Hierro oral', false),
('Poliferrón', 'Complejo hierro/ácido fólico', 'Tabletas', '60mg/0.4mg', 'Oral', '1 tableta al día', 'Hierro/Ácido fólico', false),
('Ácido Fólico Leti', 'Ácido fólico', 'Tabletas', '5mg', 'Oral', '5mg al día', 'Vitamina B9', false),
('Vitamina B12 Leti', 'Cianocobalamina', 'Ampolla', '1000 mcg/ml', 'IM', '1000 mcg al día x 7 días', 'Vitamina B12', false),
('Zinc Leti', 'Sulfato de zinc', 'Tabletas', '220mg', 'Oral', '220mg una vez al día', 'Oligoelemento', false);
